name: Deploy Admin to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/admin/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/admin/package-lock.json

      - name: Install dependencies
        working-directory: apps/admin
        run: npm ci

      - name: Type check
        working-directory: apps/admin
        run: npm run typecheck

      - name: Lint
        working-directory: apps/admin
        run: npm run lint

      - name: Build
        working-directory: apps/admin
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/admin/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
