global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@kiosk.local'
  smtp_auth_username: ''
  smtp_auth_password: ''

# Route configuration
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical'
    - match:
        severity: warning
      receiver: 'warning'

# Receivers
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://kiosk-agent:7070/api/alerts/webhook'
        send_resolved: true

  - name: 'critical'
    webhook_configs:
      - url: 'http://kiosk-agent:7070/api/alerts/webhook'
        send_resolved: true
    # Add email or other notification channels as needed
    # email_configs:
    #   - to: 'admin@example.com'

  - name: 'warning'
    webhook_configs:
      - url: 'http://kiosk-agent:7070/api/alerts/webhook'
        send_resolved: true

# Inhibit rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
